### ISSUE TITLE
Access hls.js objects from Flowplayer API

### ISSUE THREAD

**Issue by popler** [flowplayer/flowplayer-hlsjs#15]
This is not issue, rather the question. What is the easiest way to access objects from hls.js (eg. parsed leveles from manifest) directly from Flowplayer API?

**Comment by blacktrash** [comment]
@popler - the easiest way currently does not exist because there isn't any way implemented (yet).
Coincidentally you created the issue I wanted to create since quite some time actually ;-)

Exposing the hls.js API etc. is definitely on the cards and a must have. It should be done iin a way which offers the best longer-term perspective with the core player, and in view that this is not a scenario specific to this plugin. It's basically about: how to best integrate a plugin using an 'upstream' library.

A team meeting with our chief developer is planned, albeit without exact date because of other back logs. We definitely want to get this going, but please understand that we want to get the basics right. Thank you.

**Comment by popler** [comment]
Ok:) Maybe there is any option to push those object to API? I'm working on quality selector. I can add it into flowplayer-hlsjs.js file, but I prefer to make it like original quality selector, to be engine independent.

**Comment by blacktrash** [comment]
@popler - as I said: there will be, but not yet.

**Comment by popler** [comment]
@blacktrash - Ok:) I prepare manual quality selector for hlsjs:) I'm using standard quality selector for different engines.
BTW. I noticed that I don't have to manually change media sources whitelist to use hlsjs.

You can change demo (for few hours) on http://twon.popler.tv/embed/vod2.php?v=83532
I set change on nextLevel, but currentLevel method is also working.

**Comment by anaptfox** [comment]
+1

**Comment by nnarhinen** [comment]
@blacktrash IMO the best and most generic approach would be to expose it from the engine initialization. To the return value (the one where you return the object with `load()`, `pause()` etc, just add something like `hls = new Hls(hlsClientConf); engine.hls = hls;`

This way the hls object can be accessed with `flowplayer(0).engine.hls`

**Comment by blacktrash** [comment]
@nnarhinen - thanks, will take that path.

**Comment by blacktrash** [comment]
hls.js API now accessible via `engine.hlsjs`: https://github.com/flowplayer/flowplayer-hlsjs#access-to-hlsjs-api
