### ISSUE TITLE
MP3 in MP4 doesn't work in Chrome and Safari. Flowplayer should fallback?

### ISSUE THREAD

**Issue by anaptfox** [flowplayer/flowplayer-hlsjs#18]
Hi, I'm sorry I don't know if the forum or Github was the best place to put this.

So, hls.js checks this:
```javascript
MediaSource.isTypeSupported('video/mp4; codecs=“mp4a.40.34”');
```
(dailymotion/hls.js/issues/44)
This returns false in Chrome and Firefox
This is a known chrome issue:
code.google.com/…/etail?id=489520#makechanges

I haven't looked through the firefox issues yet to see if there working on it.
So, my question is, Can we get Flowplayer to fall back to the Flashed based HLS player in this case? Currently, it just errors out in hls.js

**Comment by blacktrash** [comment]
This is documented here: https://github.com/flowplayer/flowplayer-hlsjs#known-issues-and-constraints
You just have to set `hlsjs: false` for those players/clips: https://github.com/flowplayer/flowplayer-hlsjs#plugin-configuration . It's no real use to have a 'dynamic' config knob in place because once the clip is loaded and codec type recognized, it's too late. You must know the codecs in advance.
You could only implement a failover mechanism like in this demo http://demos.flowplayer.org/scripting/recover.html if for some reason you don't know in advance what codecs your streams contain.
