### ISSUE TITLE
Compatibility issue with Chrome "Adblock for Youtube" extension

### ISSUE THREAD

**Issue by mardu** [flowplayer/flowplayer-hlsjs#39]
Found a compatibility issue with Chrome "Adblock for Youtube" extension.
Steps to reproduce:

1. Enable "Adblock for Youtube" plugin.
2. Go to: http://demos.flowplayer.org/api/hlsjs.html
3. Open the Network tab on "Inspect element" tool.
4. Start the Live player demo (VOD player works normally).
5. Switch between different qualities for multiple times.

What happens:
Network inspector shows major spamming. Sometimes the whole browser crashes.

Tested on OSX 10.10.5 + Chrome 51.0.2704.106 (64-bit) and Windows 8.1 + Chrome 51.0.2704.106 m (64-bit)

I also posted this issue to the "Adblock for Youtube" developer since i am not sure who should fix it. Since this extension has 3 000 000+ users, I assume this could affect many people.

**Comment by blacktrash** [comment]
@mardu - that is caused at least in part by the stream, maybe the extension emphasizes the problem; but I can sometimes get a canceled load loops too.
The stream is quite cludgy, and the problem can be reproduced in the hls.js client demo player too: http://dailymotion.github.io/hls.js/demo/?src=http%3A%2F%2Fnasatv-lh.akamaihd.net%2Fi%2FNASA_101%40319270%2Fmaster.m3u8&enableStreaming=true&autoRecoverError=true&enableWorker=true&levelCapping=-1&defaultAudioCodec=undefined

As you can see https://github.com/dailymotion/hls.js/search?q=nasa&type=Issues&utf8=%E2%9C%93 the stream is a topic in several issues, and it's not yet handled perfectly by hls.js

We are using the stream because it's the only live stream with variants we have access to.

For the moment there's nothing to be done from the plugin site. We'll file a bug concentrating on the level switching aspect in the hls.js bug tracker - unless you beat us to it ;-)

**Comment by mardu** [comment]
Actually i discovered the issue with another live stream using a slightly modified player, but after checking the demo player, i noticed that it is a general issue.

**Comment by blacktrash** [comment]
@mardu - this is now https://github.com/dailymotion/hls.js/issues/571
If you have another sample stream where this happens, do not hesitate to mention it there.

**Comment by mardu** [comment]
Here is our testplayer: http://otse.err.ee/live/iframe/etv?src=hlsjs
However the stream has ~30% geoblocked content so it might not work all the time.

**Comment by blacktrash** [comment]
@mardu - this must be solved in the client library, so you better monitor the issue I referenced.
The stream is blocked for me. For productive debugging you'd have to make a stream available which is not blocked for the hls.js sample player: http://dailymotion.github.io/hls.js/demo/
As you noticed yourself the problem is stream dependent, so only stream samples which are available will help.

Aside remarks after a quick glance at your sample:
- normally container data-attributes are not taken into account for pure JavaScript installs: https://flowplayer.org/docs/setup.html#javascript-install
- we recommend to always load the latest assets both for the hlsjs and dashjs plugins (you are using a completely outdated plugin for the latter): https://flowplayer.org/docs/plugins.html#hlsjs-assets and https://flowplayer.org/docs/plugins.html#hlsjs-assets - apart from bugfixes, for instance hlsjs now offers hls quality/level selection: https://flowplayer.org/docs/plugins.html#hls-quality-selection
- it's usually not a bad idea to upgrade to the latest player version either

**Comment by blacktrash** [comment]
With the latest version of the plugin http://demos.flowplayer.org/api/hlsjs.html#hlsjslive works.
