### ISSUE TITLE
Google Open Spherical Camera API Live Preview

### ISSUE THREAD

**Issue by wowzaaa** [flowplayer/flowplayer-hlsjs#44]
Hey

Can i use flowplayer-hlsjs to implement Google's OSC Api?
i need to make a post request to a local ip address with { name: "camera.getLivePreview" } as parameters 
i am getting back a stream of jpegs as binary data
https://developers.google.com/streetview/open-spherical-camera/reference/camera/getlivepreview

is there a way i can use this library to handle the response?

thanks

**Comment by blacktrash** [comment]
No, I strongly doubt it.
From a quick check it doesn't produce a HLS stream.
Also Flowplayer - and hls.js for that matter - expect an URL; which _can_ be an ObjectURL or similar: http://demos.flowplayer.org/scripting/filereader.html - but you would still need a video or HLS stream which can be played.

To me this looks like you want to generate a valid HLS stream in the first place - or use an entirely different approach. Integrating it into Flowplayer would be your very last step. Basically you need _something_ which can be played by a video tag (and for the Flash failover to work 'it' would have to be playable by Flash as well).

**Comment by wowzaaa** [comment]
thanks @blacktrash 
i can officially say i am lost :)

**Comment by blacktrash** [comment]
Me too ;-)
But basically it's pretty simple: You need a 'real video' for a video tag, web video player etc. That can be VOD (a video file) or a stream (HLS).
I have no idea what OSC is capable of, but it sounds like it's generating a sequence of JPEGS.
It is possible to *transcode* an image sequence into a video or stream format, but that is normally the task of a dedicated program like ffmpeg or similar. It's not even just transmuxing because the `mjpeg` codec cannot be played by any browser.

**Comment by blacktrash** [comment]
Feel free to ask at the hls.js issue tracker, there are very knowledgable people there; in case I overlooked/misunderstood.
To me it looks like your first step would be: how do I transform OSC results into a HLS stream.
