### ISSUE TITLE
Add support for upcoming quality selection menu in Flowplayer 7

### ISSUE THREAD

**Issue by nnarhinen** [flowplayer/flowplayer-hlsjs#55]
See flowplayer/flowplayer#1080

@blacktrash Do you think hlsjs engine can work with the spec or should we modify it somehow?

**Comment by blacktrash** [comment]
Can be catered for. But see some of the conceptual problems I've outline in the core feature request.

**Comment by blacktrash** [comment]
Is the evaluation of hlsQualities configuration against actual available qualities etc. done entirely in core?

That is: Is it enough if on ready the available data on all available levels is sent to core (as player.qualities or ...?)
```js
availableLevels: {
  { value: -1 }, // label "Auto" or configured decision made in core
  { value: 0, width: 640, height: 360, bitrate: 450000 }
  /*
    width, height, bitrate depending on availability
    core decides
    1. is more than 1 level available
    2. does comparison of available levels and (default) label decision
       e.g. Math.round(bitrate/1000) + "k"
       based on sent level objects
  */
}
```
to avoid duplication of code?

If yes, should it be `api.qualities` on ready, and core does narrowing down, according to config (e.g. hlsQualities: "drive"), or should it be some "intermediate" api property?

Different scenario applies to api.quality: this must be determined by the plugin (if it differs from -1/Auto e.g. in playlists) because the plugin must set startLevel before ready. So on ready api has to just take over that level - and assign label according to sent available levels.

Or does the api expect a finalized Array of player.qualities derived and evaluated from hlsQualities conf: `[{value: -1, label: "custom"}, {value: 0, label: "SD"}`? - (implying potential code duplication - something similar must already be done for flash hls)

For the moment I am discarding the corner case scenario in a playlist there are clips with hlsQualities, and others with hlsQualities:null, but (VOD) qualities configured.
