### ISSUE TITLE
Does it support IPv6?

### ISSUE THREAD

**Issue by huanghe2015** [flowplayer/flowplayer-hlsjs#70]
When I was testing HLS source at this page:http://itv.ahau.edu.cn/player.html?channel=cctv1hd which has a m3u8 file at local machine,it doesn't work.Here is the structre of m3u8 file and log of demo test(I'm sure it does work it whit flash player when I'm watching live stream locally):
## log
cannot Load http://itv.ahau.edu.cn/hls/cctv1hd.m3u8
HTTP response code:0 
this might be a CORS issue, consider installing Allow-Control-Allow-Origin Chrome Extension,network error
## m3u8 file
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:171972
#EXT-X-TARGETDURATION:10
#EXTINF:10.000,
cctv1hd-171972.ts
#EXTINF:10.000,
cctv1hd-171973.ts
#EXTINF:10.000,
cctv1hd-171974.ts
#EXTINF:10.000,
cctv1hd-171975.ts
#EXTINF:10.000,
cctv1hd-171976.ts
#EXTINF:10.000,
cctv1hd-171977.ts
#EXTINF:10.000,
cctv1hd-171978.ts
#EXTINF:10.000,
cctv1hd-171979.ts
#EXTINF:7.120,
cctv1hd-171980.ts
#EXTINF:5.120,
cctv1hd-171981.ts
#EXTINF:8.800,
cctv1hd-171982.ts
#EXTINF:6.720,
cctv1hd-171983.ts

**Comment by bbbo** [comment]
Please post usage questions in the forums first.
The plugin does not care whether the network request is ip4 or ip6 , it relies on http(s) which is on a higher level. As the error says, most likely you did not set the  [CORS headers](https://flowplayer.org/docs/plugins.html#hlsjs-server-side)

But since the site is not public,we  cannot check.

**Comment by huanghe2015** [comment]
I had solved CORS problem in Webstorm by enabled"Can accept external connections"and"Allow unsigned requests" at local machine's web page,but the hint"hlsjs: Video file not found"still exists.
