### ISSUE TITLE
null check videoTag reference before issuing commands

### ISSUE THREAD

**Issue by josh-sachs** [flowplayer/flowplayer-hlsjs#82]
When packaged up (rollup/uglify/sfx) occasionally i see errors related to flowplayer-hlsjs calls to video actions (e.g. pause) being made against a null reference. 

e.g.
`g.pause is not a function`

I went through and modified playback commands to be issued as such: 

`videoTag && videoTag.play();`
`videoTag && videoTag.pause();`

There are some circumstances where you are already doing this (e.g. changing volume), but not in others.

**Comment by blacktrash** [comment]
Regarding volume: core does the same: https://github.com/flowplayer/flowplayer/blob/master/lib/engine/html5.js#L222-L227 (`api` is the video tag in this case).
(aside: I wonder whether I should approach the initial volume as here: https://github.com/flowplayer/flowplayer/blob/master/lib/engine/html5.js#L222-L227 )

I don't know how you package the plugin; note that there is a very obscure and hard to repro issue with webpack as well: https://github.com/flowplayer/flowplayer-hlsjs/issues/43 - which is why the official release is just concatenated.

Is this with a totally simple setup otherwise? I have never come across this in other scenarios and don't want to clutter the code for something which seems rather to point to a different problem.
If videoTag is null for every, or near every engine method, then something else must be wrong, like your build somehow manages to initialize the engine without a video tag.

**Comment by josh-sachs** [comment]
I'm not sure how it would be possible to initialize flowplayer without a video tag... flowplayer creates the tag.  

I think the difference is that flowplayer-hlsjs engine is interacting with videoTag element reference (</video> - which gets removed during teardown) whereas core is interacting with flowplayer-hlsjs engine, which is probably guaranteed not to be null until core is done with it. 

core.pause => fp-hlsjs.pause => videoTag.pause !!!videoTag no longer exists.

**Comment by blacktrash** [comment]
1. The hlsjs creates 'its own' video tag
2. Core treats other engines the same way: core.pause => html5engine.pause => videoTag.pause.

Can you reproduce this in any way when loading the Flowplayer assets the 'standard way' instead of your own build?
Please provide a _minimal_ sample page where you encounter this.

**Comment by blacktrash** [comment]
Closing.
@josh-sachs - feel free to re-open with a link to an actual example.
