### ISSUE TITLE
Video hangs at a segment

### ISSUE THREAD

**Issue by dajuric** [flowplayer/flowplayer-hlsjs#83]
The provided video is sliced to non-uniform segments where some of the segments are using different FFMpeg compression profile (fast vs main).

To reproduce the behavior a Python 3.x server can be used:
    `python -m http.server 80`

The video hangs at 7th second in Chrome, Firefox plays the video until the end MS Edge has a similar behavior as Chrome except is shows that the video is loaded (white bar spans till the end).

The video is enclosed:
[video-segments.zip](https://github.com/flowplayer/flowplayer-hlsjs/files/1202565/video-segments.zip)

**Comment by blacktrash** [comment]
Same behavior with pure hls.js. - I am not surprised ;-)
If you really want hls.js to support streams containing different profiles - if it's not caused by the broken audio time stamps - then you should take this to the hls.js bug tracker: https://github.com/video-dev/hls.js/issues/

Personally, I would just encode to one profile, this borders on begging for trouble; nevermind that (some) native implementations play it. I imagine it's just not explicitly forbidden by specs because no-one had the idea to do this ;-)
